---

- name: clean folder if needed
  shell: >
    rm -rf /tmp/concourse
  become: true

- name: tmp folder for prepare concourse
  file:
    path: /tmp/concourse
    state: directory
    mode: 0755

- name: Docker compose file
  template:
    src: templates/docker-compose.yml.j2
    dest: /tmp/concourse/docker-compose.yaml

- name: prepare keys
  shell: |
      mkdir -p keys/web keys/worker
      ssh-keygen -q -t rsa -f ./keys/web/tsa_host_key -N ''
      ssh-keygen -q -t rsa -f ./keys/web/session_signing_key -N ''
      ssh-keygen -q -t rsa -f ./keys/worker/worker_key -N ''
      cp ./keys/worker/worker_key.pub ./keys/web/authorized_worker_keys
      cp ./keys/web/tsa_host_key.pub ./keys/worker
  args:
    chdir: /tmp/concourse

- name: launch docker containers
  shell: >
    docker-compose up -d
  args:
    chdir: /tmp/concourse
